[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PHP_VERSION = "8.1"
  NODE_VERSION = "16"

# Las redirecciones necesarias para una SPA con Laravel
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Encabezados para la caché y seguridad
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
